name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://kubajastrz.com/
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v1
        with:
          runtime: node@24
          install: false

      - run: pnpm ci

      - run: |
          pnpm build
          test -f dist/index.html
          mv dist deploy/dist
          test -f deploy/dist/index.html

      - uses: kubajastrz/actions/setup-vps-ssh@v2
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          op-vps-host: op://app-kubajastrz/vps/ipv4
          op-vps-user: op://app-kubajastrz/vps/username
          op-vps-port: op://app-kubajastrz/vps/port
          op-ssh-private-key: op://app-kubajastrz/deploy-ssh-key/private key?ssh-format=openssh

      - uses: kubajastrz/actions/sync-artifacts@v2

      - uses: kubajastrz/actions/remote-deploy-static@v2
